---
title: "16S Phyloseq"
output: html_notebook
---

```{r}
require(phyloseq)
 library(parallelDist)
library(ggplot2)
```


```{r}

load("/Users/gordoncuster/Desktop/Git_Projects/BeeBread/Data/16S/DADA2outputs/dada2_outputs_16S_BeeBread.RData")
```

```{r}
metadata <- read.csv("/Users/gordoncuster/Desktop/Git_Projects/BeeBread/Data/BB_sample-metadata.txt", sep = "\t")
#append ".fastq.gz" to end of metadata to match sequence file names. 
rownames(metadata) <- paste(metadata$X, ".fastq.gz", sep = "")
```

```{r}
#assign object type to merge into phyloseq object
md <- sample_data(metadata)
otu <- otu_table(seqtab.nochim, taxa_are_rows = F)
tax_tab <- tax_table(taxa)
#check sample names of both otu table and metadata
sample_names(md)
sample_names(otu)
#since they match, you can create the phyloseq object
bb16S_orig <- phyloseq(md, otu, tax_tab)
```

Preprocessing. Creat bacterial and archael phyloseq object
```{r}
#2315 bacterial taxa
bb16S_bac <- subset_taxa(bb16S_orig, Kingdom == "Bacteria")
#9 archaea
bb16S_arch <- subset_taxa(bb16S_orig, Kingdom == "Archaea")
#2 taxa did not assign to bacteria or archea
```

Check sample depths for rarefaction
```{r}
sort(sample_sums(bb16S_bac))
test_bb16S_bac_rarefy <- rarefy_even_depth(bb16S_bac, sample.size = 2000, rngseed = 14, trimOTUs = T)
#Rarefaction depth depends on the need to retain the control samples. If thery are not really needed for the design, they we can rarefy at ~20k. If we do need them, we will need to rarefy at 2k.


#remove DilutionDTC sample. 
bb16S_bac <- subset_samples(physeq = bb16S_bac, sample_names(bb16S_bac) != "Dilution.fastq.gz")
#to move forward, we can hellinger transform and go from there.
bb16S_bac_hellinger <- transform_sample_counts(bb16S_bac, function(x) sqrt(x / sum(x)))

#maximum liklihood point estimates
bb16S_bac_ML<- transform_sample_counts(bb16S_bac, function(x) x / sum(x))
```
Rarefaction curves
```{#r}
rarecurve(t(otu_table(bb16S_bac)), step=50, cex=0.5)
rarecurve(t(otu_table(test_bb16S_bac_rarefy)), step=50, cex=0.5)
```

exploratory analysis
alpha div
```{r}
plot_richness(test_bb16S_bac_rarefy, x = "Region", measures = c("Shannon", "Observed", "Chao1"), color = "Region") + geom_boxplot()

plot_richness(test_bb16S_bac_rarefy, x = "Treatment", measures = c("Shannon", "Observed", "Chao1"), color = "Treatment") + geom_boxplot()


plot_richness(test_bb16S_bac_rarefy, x = "Region_Treatment", measures = c("Shannon", "Observed", "Chao1"), color = "Region") + geom_boxplot()
```
Wilcoxon tests of alpha diversity measures
```{r}
richness_BB16S_bac<-estimate_richness(test_bb16S_bac_rarefy, measures = c("Shannon", "Observed", "Chao1"))

richness_BB16S_bac$Region <- sample_data(test_bb16S_bac_rarefy)$Region
richness_BB16S_bac$Site <- sample_data(test_bb16S_bac_rarefy)$Site
richness_BB16S_bac$Timepoint <- sample_data(test_bb16S_bac_rarefy)$Timepoint
richness_BB16S_bac$Treatment <- sample_data(test_bb16S_bac_rarefy)$Treatment

#non Parametric tests
pairwise.wilcox.test(richness_BB16S_bac$Shannon, richness_BB16S_bac$Region)
pairwise.wilcox.test(richness_BB16S_bac$Shannon, richness_BB16S_bac$Treatment)
pairwise.wilcox.test(richness_BB16S_bac$Shannon, richness_BB16S_bac$Site)
#Significant difference for none (i.e., controls) vs. two timepoints. I'm not sure what the controls indicate so its hard to interpret. 
pairwise.wilcox.test(richness_BB16S_bac$Shannon, richness_BB16S_bac$Timepoint)


pw_wc<-function(r = "Richness Dataframe", y = "Richness Metric", g = "Grouping variable to Test"){
  print(pairwise.wilcox.test(r[,y], r[,g]))
}


pw_wc(r = richness_BB16S_bac, y = "Shannon", g = "Treatment")
pw_wc(r = richness_BB16S_bac, y = "Shannon", g = "Site")
pw_wc(r = richness_BB16S_bac, y = "Shannon", g = "Region")
pw_wc(r = richness_BB16S_bac, y = "Shannon", g = "Timepoint")


```


```{r}
#Parametric anova
mod <- aov(formula = Shannon ~ Treatment, data = richness_BB16S_bac)
plot(mod$residuals)
shapiro.test(mod$residuals)
summary(mod)
TukeyHSD(mod, which = "Treatment")

```


```{r}
sd_adonis <- data.frame(sample_data(bb16S_bac_ML))
tab_adonis <- data.frame(otu_table(bb16S_bac_ML))
dist <- parallelDist(as.matrix(tab_adonis), method = "bray")
adonis(dist~Treatment, data = sd_adonis, permutations = 1000)
ord_cap<-ordinate(physeq = bb16S_bac_ML, method = "CAP", distance = "bray", formula = ~ Region)
plot_ordination(physeq = bb16S_bac_ML, ordination = ord_cap, type = "Samples", color = "Region", shape = "Treatment" )
```

