---
title: "Core alignment with RDP representative sequences"
output: html_notebook
---
```{r}
BiocManager::install("msa")
require(msa)
```



```{r}
library(DECIPHER)
library(phangorn)
library(dada2)
#input<-read.csv("/Users/gordoncuster/Desktop/Git_Projects/BeeBread/Writing/rdp_type_strains_with_core_rep_genera.fasta", header = F)
sequences<-dada2::getSequences("/Users/gordoncuster/Desktop/Git_Projects/BeeBread/Writing/rdp_type_strains_with_core_rep_genera_cleanedup.fasta")
#tax_names <- read.csv("/Users/gordoncuster/Desktop/Git_Projects/BeeBread/Writing/rdp_type_strains_with_core_rep_genera_for_tipLabel_renaming.csv", header = T)

#sequences2<-getSequences(tax_names$Sequence)

#names(sequences2)<-tax_names$Name
alignment <- AlignSeqs(DNAStringSet(sequences, use.names = T), anchor=NA)


phang.align <- phyDat(as(alignment, "matrix"), type="DNA")

dm <- dist.ml(phang.align)
#Perform Neighbor joining

treeNJ <- NJ(dm) # Note, tip order != sequence order
#Internal maximum likelihood

fit = pml(treeNJ, data=phang.align)
#negative edges length changed to 0!

fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                    rearrangement = "stochastic", control = pml.control(trace = 0))

plot(fitGTR, cex=0.8)

```



